server:
  port: 9000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/sample_db
    username: admin
    password: password
  redis:
    host: localhost
    port: 6379
    database: 0
  session:
    store-type: redis
