version: '3'

services:
  postgresql:
    image: postgres:latest
    container_name: sample-docker_postgres_1
    ports:
      - "5432:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=sample_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - TZ=Asia/Tokyo
  redis:
    image: redis:latest
    container_name: sample-docker_redis_1
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

volumes:
  db-store: